// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Pap
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"BPM")]
            public float BPM { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"SpO2 (%)")]
            public float SpO2____ { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"GSR (kΩ)")]
            public float GSR__kΩ_ { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Temp (°C)")]
            public float Temp___C_ { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Nível de Estresse")]
            public float Nível_de_Estresse { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"BPM")]
            public float BPM { get; set; }

            [ColumnName(@"SpO2 (%)")]
            public float SpO2____ { get; set; }

            [ColumnName(@"GSR (kΩ)")]
            public float GSR__kΩ_ { get; set; }

            [ColumnName(@"Temp (°C)")]
            public float Temp___C_ { get; set; }

            [ColumnName(@"Nível de Estresse")]
            public float Nível_de_Estresse { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
